"""
Cloud SQL database component.

Creates the Cloud SQL Postgres instance, application database, app user,
and writes the generated password to Secret Manager.

Usage:
    db = Database(
        "db",
        vpc=network.vpc,
        peering=network.peering_connection,
        secrets=secrets,
    )
    db.instance       # gcp.sql.DatabaseInstance
    db.database_url   # pulumi.Output[str] — the full DATABASE_URL

Attributes exposed:
    instance     (gcp.sql.DatabaseInstance): the Cloud SQL instance
    database_url (pulumi.Output[str]): the full postgres connection URL
                 e.g. "postgresql+psycopg://appuser:<pw>@<private-ip>:5432/storyengine"
                 Written to Secret Manager as a SecretVersion in __main__.py.

Design decisions:
    - private IP only for production traffic (ipv4_enabled=True for Auth Proxy
      access from developer laptops — the public IP has no authorized networks
      so direct connections are rejected; only Auth Proxy can use this path).
    - ENTERPRISE edition with db-f1-micro (~$7/month), ZONAL availability.
      ENTERPRISE_PLUS requires db-perf-optimized-N-* tier (more expensive).
    - Random password generated by Pulumi, stored in Secret Manager under
      the db_password slot from AppSecrets. The app never reads this directly —
      it reads DATABASE_URL which embeds the password.
    - deletion_protection=False: allows pulumi destroy in dev. Set True in prod.
    - db-password-version and db.database_url are internal child resources of
      this component. The DATABASE_URL SecretVersion stays in __main__.py because
      it depends on BOTH db.database_url AND secrets.database_url.id — a
      cross-component wiring step that belongs at the orchestration level.

After applying this component (especially on first run or after recreation):
    make populate-secrets    # re-push other secret values (DATABASE_URL is
                             # written by Pulumi, not populate-secrets)
    make migrate             # run alembic upgrade head against the fresh DB

To retrieve the DB password manually:
    gcloud secrets versions access latest \\
      --secret <prefix>-db-password \\
      --project <project>
    # Or: make proxy  (connects Auth Proxy to localhost:5433)
"""

import pulumi
import pulumi_gcp as gcp
import pulumi_random as random

from components.config import APP, DB_NAME, REGION, resource_name
from components.secrets import AppSecrets

_DB_VERSION = "POSTGRES_16"
_DB_NAME = DB_NAME  # read from config (db_name key), defaults to APP if not set
_DB_USER = "appuser"


class Database(pulumi.ComponentResource):
    """
    Cloud SQL Postgres 16 instance with private IP, random password,
    and DATABASE_URL construction.

    The password is generated randomly on first run and stored in Secret Manager.
    The DATABASE_URL is constructed from the private IP and password, and exposed
    as database_url for __main__.py to write as a SecretVersion.

    Child resources (all parented to this component):
        {name}-password         random.RandomPassword  (internal, not exposed)
        {name}-password-version gcp.secretmanager.SecretVersion
        {name}-instance         gcp.sql.DatabaseInstance
        {name}-appdb            gcp.sql.Database
        {name}-appuser          gcp.sql.User

    Derived attributes (not GCP resources):
        database_url   pulumi.Output[str] — the full postgres connection string
    """

    instance: gcp.sql.DatabaseInstance
    database_url: pulumi.Output[str]

    def __init__(
        self,
        name: str,
        vpc: gcp.compute.Network,
        peering: gcp.servicenetworking.Connection,
        secrets: AppSecrets,
        opts: pulumi.ResourceOptions | None = None,
    ) -> None:
        super().__init__(f"{APP}:infra:Database", name, {}, opts)

        # Generate a random password for the database user.
        # special=False avoids characters that need URL-encoding in connection strings.
        # Pulumi stores this in its state (encrypted) and only changes it if the
        # resource is replaced. The value is also written to Secret Manager below
        # so it's always retrievable independently of Pulumi state.
        db_password = random.RandomPassword(
            f"{name}-password",
            length=32,
            special=False,
            opts=pulumi.ResourceOptions(parent=self),
        )

        # Store the generated password in Secret Manager immediately.
        # This is the single source of truth for the password — Pulumi state
        # has it too, but Secret Manager is where operators retrieve it.
        gcp.secretmanager.SecretVersion(
            f"{name}-password-version",
            secret=secrets.db_password.id,
            secret_data=db_password.result,
            opts=pulumi.ResourceOptions(parent=self),
        )

        # Cloud SQL Postgres instance with private IP only for production traffic.
        # ipv4_enabled=True enables the Auth Proxy path for local developer access
        # (no authorized_networks configured, so direct public connections are rejected).
        self.instance = gcp.sql.DatabaseInstance(
            f"{name}-instance",
            name=resource_name("postgres"),
            database_version=_DB_VERSION,
            region=REGION,
            deletion_protection=False,
            # Explicit dependency: peering must be fully established before Cloud
            # SQL is created. Without this Pulumi runs them in parallel and Cloud
            # SQL fails with "network doesn't have at least 1 private services
            # connection". Pulumi can't infer this dependency automatically because
            # the connection resource isn't referenced in the instance's arguments.
            opts=pulumi.ResourceOptions(parent=self, depends_on=[peering]),
            settings=gcp.sql.DatabaseInstanceSettingsArgs(
                tier="db-f1-micro",
                # Explicitly set ENTERPRISE edition. GCP now defaults to
                # ENTERPRISE_PLUS which requires the db-perf-optimized-N-*
                # tier family. ENTERPRISE supports db-f1-micro (~$7/month).
                edition="ENTERPRISE",
                availability_type="ZONAL",
                disk_autoresize=True,
                disk_size=10,
                disk_type="PD_SSD",
                ip_configuration=gcp.sql.DatabaseInstanceSettingsIpConfigurationArgs(
                    # Public IP enabled so the Cloud SQL Auth Proxy can connect
                    # from developer laptops for local migrations. The public IP
                    # is not accessible directly — no authorized networks are
                    # configured, so all direct connections are rejected. Only
                    # the Auth Proxy (which uses IAM auth via TLS tunnel) can use
                    # this path. Cloud Run uses the private IP via VPC egress.
                    ipv4_enabled=True,
                    private_network=vpc.id,
                    # Allows Cloud SQL to be reached by Google-internal services
                    # via direct VPC egress without a public IP.
                    enable_private_path_for_google_cloud_services=True,
                ),
                backup_configuration=gcp.sql.DatabaseInstanceSettingsBackupConfigurationArgs(
                    enabled=False,
                ),
            ),
        )

        gcp.sql.Database(
            f"{name}-appdb",
            name=_DB_NAME,
            instance=self.instance.name,
            opts=pulumi.ResourceOptions(parent=self),
        )

        gcp.sql.User(
            f"{name}-appuser",
            name=_DB_USER,
            instance=self.instance.name,
            password=db_password.result,
            opts=pulumi.ResourceOptions(parent=self),
        )

        # Construct the full DATABASE_URL from the private IP (known only after
        # Cloud SQL is created) and the generated password.
        # pulumi.Output.all() waits for both outputs to resolve before applying.
        self.database_url = pulumi.Output.all(
            self.instance.private_ip_address, db_password.result
        ).apply(
            lambda args: f"postgresql+psycopg://{_DB_USER}:{args[1]}@{args[0]}:5432/{_DB_NAME}"
        )

        self.register_outputs(
            {
                "instance": self.instance,
                "database_url": self.database_url,
            }
        )
