"""
GCS media bucket component.

Creates the private GCS bucket that stores all user-uploaded media for the app.

Usage:
    storage = MediaBucket("storage")
    # Access the bucket resource:
    storage.bucket  # gcp.storage.Bucket

Attributes exposed:
    bucket (gcp.storage.Bucket): the GCS bucket resource

Design decisions:
    - uniform_bucket_level_access: disables per-object ACLs; all access
      is controlled purely through IAM bindings. Cleaner and more auditable.
    - public_access_prevention="enforced": no one can ever make this bucket
      or its objects public, even accidentally. All access goes through signed URLs.
    - The bucket name is fixed via MEDIA_BUCKET_NAME from config (includes a
      random suffix set in media_bucket_suffix — immutable, globally unique).

To use in a new project:
    Set app, stack name, and media_bucket_suffix in Pulumi.<stack>.yaml.
    Generate the suffix with: openssl rand -hex 2
    NEVER change media_bucket_suffix after first deploy — it recreates the
    bucket and loses all stored media.
"""

import pulumi
import pulumi_gcp as gcp

from components.config import APP, MEDIA_BUCKET_NAME, REGION


class MediaBucket(pulumi.ComponentResource):
    """
    GCS bucket for storing private user media (images, uploads, etc.).

    All access is enforced through IAM — objects are never publicly readable.
    Signed URLs (generated by the backend) are the only way to serve content
    to end users.

    Child resources (all parented to this component):
        {name}-bucket   gcp.storage.Bucket
    """

    bucket: gcp.storage.Bucket

    def __init__(
        self,
        name: str,
        opts: pulumi.ResourceOptions | None = None,
    ) -> None:
        super().__init__(f"{APP}:infra:MediaBucket", name, {}, opts)

        self.bucket = gcp.storage.Bucket(
            f"{name}-bucket",
            name=MEDIA_BUCKET_NAME,
            location=REGION,
            uniform_bucket_level_access=True,
            public_access_prevention="enforced",
            opts=pulumi.ResourceOptions(parent=self),
        )

        self.register_outputs({"bucket": self.bucket})
