encryptionsalt: v1:sW+JQABkRHo=:v1:7J9KOOOv28snXCef:bsFSX1NP/El1IPwSZCzRTWoV29ZT8g==
config:
  gcp:project: shared-apps-infrastructure
  gcp:region: europe-west2
  storyengine-infra:image_tag: cc5474b
  storyengine-infra:domain: app.ohgraffy.com
  storyengine-infra:api_domain: api.ohgraffy.com
  storyengine-infra:landing_domain: ohgraffy.com
  storyengine-infra:csrf_cookie_domain: ohgraffy.com
  storyengine-infra:media_bucket_suffix: x7k2
  storyengine-infra:github_repo: anudeep22003/organism
  storyengine-infra:google_oauth_client_id: 198254519613-2lqv10fqhpm5731lhf2192n6tpdalo1h.apps.googleusercontent.com
  storyengine-infra:stripe_customer_portal_url: https://billing.stripe.com/p/login/fZu7sK4PB0mUgb5ftzdwc00
