encryptionsalt: v1:sW+JQABkRHo=:v1:7J9KOOOv28snXCef:bsFSX1NP/El1IPwSZCzRTWoV29ZT8g==
config:
  gcp:project: shared-apps-infrastructure
  gcp:region: europe-west2
  storyengine-infra:image_tag: 1236fcc
  storyengine-infra:domain: app.dekatha.com
  storyengine-infra:api_domain: api.dekatha.com
  storyengine-infra:media_bucket_suffix: x7k2
  storyengine-infra:github_repo: anudeep22003/organism
  storyengine-infra:google_oauth_client_id: 198254519613-2lqv10fqhpm5731lhf2192n6tpdalo1h.apps.googleusercontent.com
