"""add stripe events table for raw logging every stripe event

Revision ID: 15ebf715538f
Revises: ca58279f826b
Create Date: 2026-05-09 17:01:10.993340

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15ebf715538f"
down_revision: Union[str, Sequence[str], None] = "ca58279f826b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stripe_event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("api_version", sa.String(length=64), nullable=True),
        sa.Column("customer_id", sa.String(length=255), nullable=True),
        sa.Column("subscription_id", sa.String(length=255), nullable=True),
        sa.Column("invoice_id", sa.String(length=255), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="stripe",
    )
    op.create_index(
        "ix_event_customer_id", "event", ["customer_id"], unique=False, schema="stripe"
    )
    op.create_index(
        "ix_event_type_received_at",
        "event",
        ["event_type", "received_at"],
        unique=False,
        schema="stripe",
    )
    op.create_index(
        "ix_stripe_event_event_type",
        "event",
        ["event_type"],
        unique=False,
        schema="stripe",
    )
    op.create_index(
        "ix_stripe_event_stripe_event_id",
        "event",
        ["stripe_event_id"],
        unique=True,
        schema="stripe",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_stripe_event_stripe_event_id", table_name="event", schema="stripe"
    )
    op.drop_index("ix_stripe_event_event_type", table_name="event", schema="stripe")
    op.drop_index("ix_event_type_received_at", table_name="event", schema="stripe")
    op.drop_index("ix_event_customer_id", table_name="event", schema="stripe")
    op.drop_table("event", schema="stripe")
    # ### end Alembic commands ###
