"""transition state from jsonb to relational data while keeping backward compatibility

Revision ID: 1ae41d62182d
Revises: 3422c73da501
Create Date: 2026-02-08 16:08:13.309511

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ae41d62182d"
down_revision: Union[str, Sequence[str], None] = "3422c73da501"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "render_job",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("renderable_id", sa.UUID(), nullable=False),
        sa.Column(
            "renderable_type",
            sa.Enum("CHARACTER", "PANEL", name="renderable_type"),
            nullable=False,
        ),
        sa.Column("output_url", sa.Text(), nullable=True),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("inputs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("user_input_text", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", name="render_job_status"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "character",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("brief", sa.Text(), nullable=False),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("user_input_text", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column(
            "reference_image_urls",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "slug", name="uq_character_user_slug"),
    )
    op.create_table(
        "story",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("story_text", sa.Text(), nullable=False),
        sa.Column("user_input_text", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "comic_panel",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("panel_order", sa.Integer(), nullable=False),
        sa.Column("background", sa.Text(), nullable=False),
        sa.Column("dialogue", sa.Text(), nullable=False),
        sa.Column("user_input_text", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["story_id"], ["story.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("story_id", "panel_order", name="uq_story_panel_order"),
    )
    op.create_table(
        "story_character",
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["story_id"], ["story.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("story_id", "character_id"),
    )
    op.create_table(
        "panel_character",
        sa.Column("panel_id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["panel_id"], ["comic_panel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("panel_id", "character_id"),
    )
    # Backfill existing project rows with an empty JSON object so the NOT NULL
    # constraint doesn't blow up. We then drop the server_default so future
    # inserts are forced to provide `meta` explicitly (the ORM default=dict
    # handles this at the application level).
    op.add_column(
        "project",
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
    )

    op.alter_column("project", "meta", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "meta")
    op.drop_table("panel_character")
    op.drop_table("story_character")
    op.drop_table("comic_panel")
    op.drop_table("story")
    op.drop_table("character")
    op.drop_table("render_job")
    # ### end Alembic commands ###
