"""migrate image table to polymorphic target_id and add panel tables

Revision ID: 49f4ab84e6e6
Revises: d85baa6a8985
Create Date: 2026-03-31 02:10:00.155568

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "49f4ab84e6e6"
down_revision: Union[str, Sequence[str], None] = "d85baa6a8985"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "panel",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("source_event_id", sa.UUID(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_event_id"], ["edit_event.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["story_id"], ["story.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "panel_character",
        sa.Column("panel_id", sa.UUID(), nullable=False),
        sa.Column("character_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["panel_id"], ["panel.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("panel_id", "character_id"),
    )
    # Add target_id as nullable first, backfill from character_id, then set NOT NULL
    op.add_column("image", sa.Column("target_id", sa.UUID(), nullable=True))
    op.execute("UPDATE image SET target_id = character_id")
    op.alter_column("image", "target_id", nullable=False)
    op.drop_constraint(op.f("image_character_id_fkey"), "image", type_="foreignkey")
    op.drop_column("image", "character_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "image",
        sa.Column("character_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        op.f("image_character_id_fkey"),
        "image",
        "character",
        ["character_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("image", "target_id")
    op.drop_table("panel_character")
    op.drop_table("panel")
    # ### end Alembic commands ###
