"""adding stripe session table

Revision ID: 54a345ce08e5
Revises: 8361aab32998
Create Date: 2026-05-04 16:22:47.269223

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54a345ce08e5"
down_revision: Union[str, Sequence[str], None] = "8361aab32998"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "checkout_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("stripe_session_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_customer_record_id", sa.UUID(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("mode", sa.String(length=50), nullable=False),
        sa.Column("amount_total", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("price_id", sa.String(length=255), nullable=True),
        sa.Column("intent", sa.String(length=100), nullable=False),
        sa.Column("stripe_status", sa.String(length=20), nullable=False),
        sa.Column("payment_status", sa.String(length=30), nullable=True),
        sa.Column("fulfillment_status", sa.String(length=20), nullable=False),
        sa.Column("fulfillment_error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["stripe_customer_record_id"], ["stripe_customer.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checkout_session_stripe_customer_id"),
        "checkout_session",
        ["stripe_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checkout_session_stripe_customer_record_id"),
        "checkout_session",
        ["stripe_customer_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checkout_session_stripe_payment_intent_id"),
        "checkout_session",
        ["stripe_payment_intent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checkout_session_stripe_session_id"),
        "checkout_session",
        ["stripe_session_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_checkout_session_stripe_subscription_id"),
        "checkout_session",
        ["stripe_subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checkout_session_user_id"),
        "checkout_session",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_checkout_session_user_id"), table_name="checkout_session")
    op.drop_index(
        op.f("ix_checkout_session_stripe_subscription_id"),
        table_name="checkout_session",
    )
    op.drop_index(
        op.f("ix_checkout_session_stripe_session_id"), table_name="checkout_session"
    )
    op.drop_index(
        op.f("ix_checkout_session_stripe_payment_intent_id"),
        table_name="checkout_session",
    )
    op.drop_index(
        op.f("ix_checkout_session_stripe_customer_record_id"),
        table_name="checkout_session",
    )
    op.drop_index(
        op.f("ix_checkout_session_stripe_customer_id"), table_name="checkout_session"
    )
    op.drop_table("checkout_session")
    # ### end Alembic commands ###
