"""simplify the image table, remove variants from picture

Revision ID: 600fb91bc05b
Revises: cea593096780
Create Date: 2026-03-22 16:10:11.366839

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "600fb91bc05b"
down_revision: Union[str, Sequence[str], None] = "cea593096780"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "image", sa.Column("content_type", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "image", sa.Column("discriminator_key", sa.String(length=255), nullable=False)
    )
    op.drop_index(op.f("ix_image_format"), table_name="image")
    op.drop_index(op.f("ix_image_image_type"), table_name="image")
    op.drop_index(op.f("ix_image_variant"), table_name="image")
    op.create_index(
        op.f("ix_image_discriminator_key"), "image", ["discriminator_key"], unique=False
    )
    op.drop_column("image", "image_type")
    op.drop_column("image", "variant")
    op.drop_column("image", "format")
    op.drop_column("image", "filename")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "image",
        sa.Column(
            "filename", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "image",
        sa.Column(
            "format", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "image",
        sa.Column(
            "variant", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "image",
        sa.Column(
            "image_type", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_image_discriminator_key"), table_name="image")
    op.create_index(op.f("ix_image_variant"), "image", ["variant"], unique=False)
    op.create_index(op.f("ix_image_image_type"), "image", ["image_type"], unique=False)
    op.create_index(op.f("ix_image_format"), "image", ["format"], unique=False)
    op.drop_column("image", "discriminator_key")
    op.drop_column("image", "content_type")
    # ### end Alembic commands ###
