"""add payment plan catalog

Revision ID: 79ef6688c75d
Revises: 1831e46d4370
Create Date: 2026-05-22 07:27:44.084425

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "79ef6688c75d"
down_revision: Union[str, Sequence[str], None] = "1831e46d4370"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("stripe_price_id", sa.String(length=255), nullable=False),
        sa.Column("entitlement_feature", sa.String(length=255), nullable=False),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("amount_minor", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("interval", sa.String(length=32), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_plan_active_sort_order", "plan", ["is_active", "sort_order"], unique=False
    )
    op.create_index("ix_plan_plan_id", "plan", ["plan_id"], unique=True)
    op.create_index("ix_plan_stripe_price_id", "plan", ["stripe_price_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_plan_stripe_price_id", table_name="plan")
    op.drop_index("ix_plan_plan_id", table_name="plan")
    op.drop_index("ix_plan_active_sort_order", table_name="plan")
    op.drop_table("plan")
    # ### end Alembic commands ###
