"""adding stripe customer

Revision ID: 8361aab32998
Revises: 3c55f3bd4494
Create Date: 2026-05-02 19:54:23.958656

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8361aab32998"
down_revision: Union[str, Sequence[str], None] = "3c55f3bd4494"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripe_customer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_object", sa.String(length=50), nullable=False),
        sa.Column("livemode", sa.Boolean(), nullable=False),
        sa.Column(
            "raw_stripe_object", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("stripe_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stripe_customer_stripe_customer_id"),
        "stripe_customer",
        ["stripe_customer_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_stripe_customer_user_id"), "stripe_customer", ["user_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_stripe_customer_user_id"), table_name="stripe_customer")
    op.drop_index(
        op.f("ix_stripe_customer_stripe_customer_id"), table_name="stripe_customer"
    )
    op.drop_table("stripe_customer")
    # ### end Alembic commands ###
