"""add subscription invoice and entitlement models

Revision ID: 83cfc31b233c
Revises: a65facc94664
Create Date: 2026-05-10 17:15:40.281708

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83cfc31b233c"
down_revision: Union[str, Sequence[str], None] = "a65facc94664"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entitlement",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("feature", sa.String(length=255), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_entitlement_active_lookup",
        "entitlement",
        ["user_id", "feature", "valid_until"],
        unique=False,
    )
    op.create_index(
        "ix_entitlement_user_feature",
        "entitlement",
        ["user_id", "feature"],
        unique=False,
    )
    op.create_table(
        "subscription",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("stripe_customer_record_id", sa.UUID(), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("price_id", sa.String(length=255), nullable=False),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trial_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["stripe_customer_record_id"], ["stripe.customer.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="stripe",
    )
    op.create_index(
        "ix_subscription_stripe_customer_id",
        "subscription",
        ["stripe_customer_id"],
        unique=False,
        schema="stripe",
    )
    op.create_index(
        "ix_subscription_stripe_customer_record_id",
        "subscription",
        ["stripe_customer_record_id"],
        unique=False,
        schema="stripe",
    )
    op.create_index(
        "ix_subscription_stripe_subscription_id",
        "subscription",
        ["stripe_subscription_id"],
        unique=True,
        schema="stripe",
    )
    op.create_index(
        "ix_subscription_user_id",
        "subscription",
        ["user_id"],
        unique=False,
        schema="stripe",
    )
    op.create_table(
        "invoice",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subscription_id", sa.UUID(), nullable=True),
        sa.Column("stripe_invoice_id", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("amount_paid", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("period_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["stripe.subscription.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="stripe",
    )
    op.create_index(
        "ix_invoice_stripe_invoice_id",
        "invoice",
        ["stripe_invoice_id"],
        unique=True,
        schema="stripe",
    )
    op.create_index(
        "ix_invoice_subscription_id",
        "invoice",
        ["subscription_id"],
        unique=False,
        schema="stripe",
    )
    op.create_index(
        "ix_invoice_user_id", "invoice", ["user_id"], unique=False, schema="stripe"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_invoice_user_id", table_name="invoice", schema="stripe")
    op.drop_index("ix_invoice_subscription_id", table_name="invoice", schema="stripe")
    op.drop_index("ix_invoice_stripe_invoice_id", table_name="invoice", schema="stripe")
    op.drop_table("invoice", schema="stripe")
    op.drop_index("ix_subscription_user_id", table_name="subscription", schema="stripe")
    op.drop_index(
        "ix_subscription_stripe_subscription_id",
        table_name="subscription",
        schema="stripe",
    )
    op.drop_index(
        "ix_subscription_stripe_customer_record_id",
        table_name="subscription",
        schema="stripe",
    )
    op.drop_index(
        "ix_subscription_stripe_customer_id", table_name="subscription", schema="stripe"
    )
    op.drop_table("subscription", schema="stripe")
    op.drop_index("ix_entitlement_user_feature", table_name="entitlement")
    op.drop_index("ix_entitlement_active_lookup", table_name="entitlement")
    op.drop_table("entitlement")
    # ### end Alembic commands ###
