"""change story.user_input_text from array to text

Revision ID: 9baf8f6a5cf0
Revises: b5c95ec4495a
Create Date: 2026-02-28 13:27:55.561951

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9baf8f6a5cf0"
down_revision: Union[str, Sequence[str], None] = "b5c95ec4495a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "story",
        "user_input_text",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=sa.Text(),
        existing_nullable=False,
        server_default=sa.text("''"),
        postgresql_using="array_to_string(user_input_text, '\n')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "story",
        "user_input_text",
        existing_type=sa.Text(),
        type_=postgresql.ARRAY(sa.VARCHAR()),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
