"""adding name field to user table

Revision ID: a65facc94664
Revises: f02ea0a1e56f
Create Date: 2026-05-09 17:53:47.325120

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a65facc94664"
down_revision: Union[str, Sequence[str], None] = "f02ea0a1e56f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "name")
    # ### end Alembic commands ###
