"""add url field to character table

Revision ID: ae12d4aed74a
Revises: c7e01ef411e3
Create Date: 2026-03-12 22:56:11.884179

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae12d4aed74a"
down_revision: Union[str, Sequence[str], None] = "c7e01ef411e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("character", sa.Column("render_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("character", "render_url")
    # ### end Alembic commands ###
