"""drop unused tables: character, story_character, scene, scene_character, render_job

Revision ID: b5c95ec4495a
Revises: ced34aea1df9
Create Date: 2026-02-27 20:05:43.420079

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5c95ec4495a"
down_revision: Union[str, Sequence[str], None] = "ced34aea1df9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scene_character")
    op.drop_table("story_character")
    op.drop_table("render_job")
    op.drop_table("scene")
    op.drop_table("character")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scene_character",
        sa.Column("scene_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("character_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
            name=op.f("panel_character_character_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scene_id"],
            ["scene.id"],
            name=op.f("panel_character_panel_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "scene_id", "character_id", name=op.f("panel_character_pkey")
        ),
    )
    op.create_table(
        "character",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("brief", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_input_text",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "reference_image_urls",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="character_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="character_pkey"),
        sa.UniqueConstraint(
            "user_id",
            "slug",
            name="uq_character_user_slug",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "story_character",
        sa.Column("story_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("character_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["character.id"],
            name=op.f("story_character_character_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["story.id"],
            name=op.f("story_character_story_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "story_id", "character_id", name=op.f("story_character_pkey")
        ),
    )
    op.create_table(
        "render_job",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("renderable_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "renderable_type",
            postgresql.ENUM("CHARACTER", "PANEL", name="renderable_type"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("output_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("prompt", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "inputs",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "user_input_text",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM("PENDING", "COMPLETED", "FAILED", name="render_job_status"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("render_job_pkey")),
    )
    op.create_table(
        "scene",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("story_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("scene_order", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("background", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("dialogue", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "user_input_text",
            postgresql.ARRAY(sa.VARCHAR()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["story.id"],
            name=op.f("comic_panel_story_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("comic_panel_pkey")),
        sa.UniqueConstraint(
            "story_id",
            "scene_order",
            name=op.f("uq_story_scene_order"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    # ### end Alembic commands ###
