"""add edit_event table and story.source_event_id

Revision ID: bdadece3a90f
Revises: 9baf8f6a5cf0
Create Date: 2026-02-28 22:42:32.612194

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdadece3a90f"
down_revision: Union[str, Sequence[str], None] = "9baf8f6a5cf0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edit_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("operation_type", sa.String(length=50), nullable=False),
        sa.Column("user_instruction", sa.Text(), nullable=False),
        sa.Column(
            "input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "output_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_edit_event_project_created",
        "edit_event",
        ["project_id", sa.text("created_at DESC")],
    )
    op.create_index(
        "ix_edit_event_target_created",
        "edit_event",
        ["target_type", "target_id", sa.text("created_at DESC")],
    )
    op.add_column("story", sa.Column("source_event_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_story_source_event_id", "story", "edit_event", ["source_event_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_story_source_event_id", "story", type_="foreignkey")
    op.drop_column("story", "source_event_id")
    op.drop_index("ix_edit_event_target_created", table_name="edit_event")
    op.drop_index("ix_edit_event_project_created", table_name="edit_event")
    op.drop_table("edit_event")
    # ### end Alembic commands ###
