"""adding stripe schema to namespace stripe data, modifying old to move to public schema explicitly

Revision ID: ca58279f826b
Revises: 54a345ce08e5
Create Date: 2026-05-09 09:07:45.637943

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca58279f826b"
down_revision: Union[str, Sequence[str], None] = "54a345ce08e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS stripe")
    op.create_table(
        "stripe_customer",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=False),
        sa.Column("stripe_object", sa.String(length=50), nullable=False),
        sa.Column("livemode", sa.Boolean(), nullable=False),
        sa.Column(
            "raw_stripe_object", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("stripe_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["public.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="stripe",
    )
    op.create_index(
        op.f("ix_stripe_stripe_customer_stripe_customer_id"),
        "stripe_customer",
        ["stripe_customer_id"],
        unique=True,
        schema="stripe",
    )
    op.create_index(
        op.f("ix_stripe_stripe_customer_user_id"),
        "stripe_customer",
        ["user_id"],
        unique=True,
        schema="stripe",
    )
    op.create_table(
        "checkout_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("stripe_session_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_customer_record_id", sa.UUID(), nullable=False),
        sa.Column("stripe_customer_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_subscription_id", sa.String(length=255), nullable=True),
        sa.Column("mode", sa.String(length=50), nullable=False),
        sa.Column("amount_total", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("price_id", sa.String(length=255), nullable=True),
        sa.Column("intent", sa.String(length=100), nullable=False),
        sa.Column("stripe_status", sa.String(length=20), nullable=False),
        sa.Column("payment_status", sa.String(length=30), nullable=True),
        sa.Column("fulfillment_status", sa.String(length=20), nullable=False),
        sa.Column("fulfillment_error", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fulfilled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["stripe_customer_record_id"],
            ["stripe.stripe_customer.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["public.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="stripe",
    )
    op.create_index(
        op.f("ix_stripe_checkout_session_stripe_customer_id"),
        "checkout_session",
        ["stripe_customer_id"],
        unique=False,
        schema="stripe",
    )
    op.create_index(
        op.f("ix_stripe_checkout_session_stripe_customer_record_id"),
        "checkout_session",
        ["stripe_customer_record_id"],
        unique=False,
        schema="stripe",
    )
    op.create_index(
        op.f("ix_stripe_checkout_session_stripe_payment_intent_id"),
        "checkout_session",
        ["stripe_payment_intent_id"],
        unique=False,
        schema="stripe",
    )
    op.create_index(
        op.f("ix_stripe_checkout_session_stripe_session_id"),
        "checkout_session",
        ["stripe_session_id"],
        unique=True,
        schema="stripe",
    )
    op.create_index(
        op.f("ix_stripe_checkout_session_stripe_subscription_id"),
        "checkout_session",
        ["stripe_subscription_id"],
        unique=False,
        schema="stripe",
    )
    op.create_index(
        op.f("ix_stripe_checkout_session_user_id"),
        "checkout_session",
        ["user_id"],
        unique=False,
        schema="stripe",
    )
    op.drop_index(
        op.f("ix_checkout_session_stripe_customer_id"), table_name="checkout_session"
    )
    op.drop_index(
        op.f("ix_checkout_session_stripe_customer_record_id"),
        table_name="checkout_session",
    )
    op.drop_index(
        op.f("ix_checkout_session_stripe_payment_intent_id"),
        table_name="checkout_session",
    )
    op.drop_index(
        op.f("ix_checkout_session_stripe_session_id"), table_name="checkout_session"
    )
    op.drop_index(
        op.f("ix_checkout_session_stripe_subscription_id"),
        table_name="checkout_session",
    )
    op.drop_index(op.f("ix_checkout_session_user_id"), table_name="checkout_session")
    op.drop_table("checkout_session")
    op.drop_index(
        op.f("ix_stripe_customer_stripe_customer_id"), table_name="stripe_customer"
    )
    op.drop_index(op.f("ix_stripe_customer_user_id"), table_name="stripe_customer")
    op.drop_table("stripe_customer")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stripe_customer",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "stripe_customer_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "stripe_object", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column("livemode", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "raw_stripe_object",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "stripe_created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "synced_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name="stripe_customer_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="stripe_customer_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("ix_stripe_customer_user_id"), "stripe_customer", ["user_id"], unique=True
    )
    op.create_index(
        op.f("ix_stripe_customer_stripe_customer_id"),
        "stripe_customer",
        ["stripe_customer_id"],
        unique=True,
    )
    op.create_table(
        "checkout_session",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "stripe_session_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "stripe_customer_record_id", sa.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "stripe_customer_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "stripe_payment_intent_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "stripe_subscription_id",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("mode", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("amount_total", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "currency", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
        sa.Column(
            "price_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "intent", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "stripe_status", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "payment_status", sa.VARCHAR(length=30), autoincrement=False, nullable=True
        ),
        sa.Column(
            "fulfillment_status",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "fulfillment_error", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "completed_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "fulfilled_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "raw",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["stripe_customer_record_id"],
            ["stripe_customer.id"],
            name=op.f("checkout_session_stripe_customer_record_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("checkout_session_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("checkout_session_pkey")),
    )
    op.create_index(
        op.f("ix_checkout_session_user_id"),
        "checkout_session",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checkout_session_stripe_subscription_id"),
        "checkout_session",
        ["stripe_subscription_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checkout_session_stripe_session_id"),
        "checkout_session",
        ["stripe_session_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_checkout_session_stripe_payment_intent_id"),
        "checkout_session",
        ["stripe_payment_intent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checkout_session_stripe_customer_record_id"),
        "checkout_session",
        ["stripe_customer_record_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checkout_session_stripe_customer_id"),
        "checkout_session",
        ["stripe_customer_id"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_stripe_checkout_session_user_id"),
        table_name="checkout_session",
        schema="stripe",
    )
    op.drop_index(
        op.f("ix_stripe_checkout_session_stripe_subscription_id"),
        table_name="checkout_session",
        schema="stripe",
    )
    op.drop_index(
        op.f("ix_stripe_checkout_session_stripe_session_id"),
        table_name="checkout_session",
        schema="stripe",
    )
    op.drop_index(
        op.f("ix_stripe_checkout_session_stripe_payment_intent_id"),
        table_name="checkout_session",
        schema="stripe",
    )
    op.drop_index(
        op.f("ix_stripe_checkout_session_stripe_customer_record_id"),
        table_name="checkout_session",
        schema="stripe",
    )
    op.drop_index(
        op.f("ix_stripe_checkout_session_stripe_customer_id"),
        table_name="checkout_session",
        schema="stripe",
    )
    op.drop_table("checkout_session", schema="stripe")
    op.drop_index(
        op.f("ix_stripe_stripe_customer_user_id"),
        table_name="stripe_customer",
        schema="stripe",
    )
    op.drop_index(
        op.f("ix_stripe_stripe_customer_stripe_customer_id"),
        table_name="stripe_customer",
        schema="stripe",
    )
    op.drop_table("stripe_customer", schema="stripe")
    op.execute("DROP SCHEMA IF EXISTS stripe CASCADE")
    # ### end Alembic commands ###
