"""add fields to image table

Revision ID: ca8860cfc8dc
Revises: d0eed85a6b37
Create Date: 2026-03-17 21:43:12.018743

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca8860cfc8dc"
down_revision: Union[str, Sequence[str], None] = "d0eed85a6b37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("image", sa.Column("size_bytes", sa.Integer(), nullable=False))
    op.add_column("image", sa.Column("has_thumb", sa.Boolean(), nullable=False))
    op.add_column("image", sa.Column("has_preview", sa.Boolean(), nullable=False))
    op.add_column(
        "image", sa.Column("image_type", sa.String(length=255), nullable=False)
    )
    op.create_index(op.f("ix_image_format"), "image", ["format"], unique=False)
    op.create_index(op.f("ix_image_image_type"), "image", ["image_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_image_image_type"), table_name="image")
    op.drop_index(op.f("ix_image_format"), table_name="image")
    op.drop_column("image", "image_type")
    op.drop_column("image", "has_preview")
    op.drop_column("image", "has_thumb")
    op.drop_column("image", "size_bytes")
    # ### end Alembic commands ###
