"""simplify image table use variant, rather than has_thumb and has_preview

Revision ID: cea593096780
Revises: ca8860cfc8dc
Create Date: 2026-03-20 20:04:55.911824

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cea593096780"
down_revision: Union[str, Sequence[str], None] = "ca8860cfc8dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("image", sa.Column("filename", sa.String(length=255), nullable=False))
    op.add_column("image", sa.Column("variant", sa.String(length=255), nullable=False))
    op.create_index(op.f("ix_image_variant"), "image", ["variant"], unique=False)
    op.drop_column("image", "has_preview")
    op.drop_column("image", "has_thumb")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "image",
        sa.Column("has_thumb", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "image",
        sa.Column("has_preview", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_image_variant"), table_name="image")
    op.drop_column("image", "variant")
    op.drop_column("image", "filename")
    # ### end Alembic commands ###
