"""remove dummy field

Revision ID: d85baa6a8985
Revises: c7a266e72c18
Create Date: 2026-03-29 14:43:43.526003

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "d85baa6a8985"
down_revision: Union[str, Sequence[str], None] = "c7a266e72c18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
