DEFAULT_ENTITLEMENT_FEATURE = "pro_tier"

PRICE_ID_TO_FEATURE: dict[str, str] = {
    "price_1TTLxCAMWKJyocPOBfg70ec9": DEFAULT_ENTITLEMENT_FEATURE,
    "price_1TTLpLAMWKJyocPOzDFvIMFG": DEFAULT_ENTITLEMENT_FEATURE,
    "price_1TVSvzAMWKJyocPOhf76pKXx": DEFAULT_ENTITLEMENT_FEATURE,
    "price_1TVTLYAMWKJyocPOEzUSFEIT": DEFAULT_ENTITLEMENT_FEATURE,
    "price_1TVTbWAMWKJyocPO4ayR6keZ": DEFAULT_ENTITLEMENT_FEATURE,
    "price_1Tnfp5AF0eTxrB9NN5JOVAuJ": DEFAULT_ENTITLEMENT_FEATURE,
}


def resolve_feature_for_price(price_id: str) -> str:
    return PRICE_ID_TO_FEATURE.get(price_id, DEFAULT_ENTITLEMENT_FEATURE)
