import { Link } from "react-router"

export function PrivacyPolicy() {
  return (
    <div className="min-h-screen">
      <header className="border-b border-border">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center">
          <Link to="/" className="text-lg font-semibold tracking-tight">
            oh<span className="text-giraffy-body">graffy</span>
          </Link>
        </div>
      </header>
      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-muted-foreground mb-12">Last updated: June 5, 2026</p>

        <div className="space-y-8 text-muted-foreground leading-relaxed">
          <p>
            The privacy of your data is important to us. Your data is yours, not ours. This policy
            explains what we collect, why, and how we handle it. We never sell your personal data.
          </p>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">1. What We Collect and Why</h2>

            <h3 className="font-medium text-foreground mt-4 mb-2">Identity and Access</h3>
            <p>
              When you sign up via Google SSO, we receive your name and email address. We use this to
              identify your account and communicate with you about the Service.
            </p>

            <h3 className="font-medium text-foreground mt-4 mb-2">Billing Information</h3>
            <p>
              If you subscribe to a paid plan, your payment is processed by Stripe. We do not store
              your credit card number or banking details. Stripe provides us with a token representing
              your payment method and basic transaction records (amount, date, status).
            </p>

            <h3 className="font-medium text-foreground mt-4 mb-2">Content You Create</h3>
            <p className="mb-2">When you use Ohgraffy, we store:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Your story inputs and prompts</li>
              <li>The stories generated from your inputs</li>
              <li>Images you upload (e.g. character references)</li>
              <li>Images generated by the Service</li>
              <li>Completed comics</li>
              <li>Edits you make to stories and comics</li>
            </ul>
            <p className="mt-2">
              This content is stored solely to provide the Service to you. We do not use your content
              to train AI models, sell to third parties, or for any purpose other than delivering the
              features you use.
            </p>

            <h3 className="font-medium text-foreground mt-4 mb-2">Usage Data</h3>
            <p>
              We collect anonymized usage data through PostHog and Google Analytics: pages visited,
              features used, button clicks, errors encountered. This helps us understand how the
              product is used and fix problems. We do not build advertising profiles from this data.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">2. Third-Party Services</h2>
            <p className="mb-2">We use the following services to operate Ohgraffy:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><span className="text-foreground">Google SSO</span> for authentication. Google receives confirmation that you signed in; we receive your name and email.</li>
              <li><span className="text-foreground">Stripe</span> for payment processing. Stripe handles your payment details under their own privacy policy.</li>
              <li><span className="text-foreground">PostHog</span> for product analytics and error tracking. Collects anonymized usage events.</li>
              <li><span className="text-foreground">Google Analytics</span> for website traffic analysis. Collects anonymized page view data.</li>
            </ul>
            <p className="mt-2">Each service operates under its own privacy policy. We only share the minimum data necessary for each service to function.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">3. When We Access Your Data</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>To provide the Service: your content is processed to generate comics and deliver features you request.</li>
              <li>To troubleshoot: if you report a bug, we may look at your account data to diagnose the issue.</li>
              <li>To enforce our terms: if we receive a report of abuse, we may review the flagged content.</li>
              <li>When required by law: we will comply with valid legal requests (court orders, subpoenas) but will notify you when legally permitted.</li>
            </ul>
            <p className="mt-2">We do not access your content for any other reason. We do not mine your data for insights, trends, or profiling.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">4. Your Rights</h2>
            <p className="mb-2">You have the right to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li><span className="text-foreground">Access</span> your personal data. You can export your stories and comics at any time.</li>
              <li><span className="text-foreground">Correct</span> inaccurate data. Update your profile through your account settings.</li>
              <li><span className="text-foreground">Delete</span> your data. Contact us at support@ohgraffy.com and we will delete your account and all associated data within 30 days.</li>
              <li><span className="text-foreground">Object</span> to data processing. You can opt out of analytics tracking by disabling cookies in your browser.</li>
              <li><span className="text-foreground">Portability</span>. Request a copy of your data in a standard format.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">5. Data Security</h2>
            <p>
              All data is transmitted over HTTPS (TLS encryption in transit). Stored data is encrypted
              at rest. We follow industry-standard security practices to protect your information.
              However, no method of transmission over the internet is 100% secure, and we cannot
              guarantee absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">6. Data Retention</h2>
            <p>
              We retain your data for as long as your account is active. If you delete content within
              the app, it is removed from our servers within 30 days. If you delete your account, all
              data is permanently removed within 30 days.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">7. Cookies</h2>
            <p>
              We use essential cookies for authentication and session management. We use analytics
              cookies (PostHog, Google Analytics) to understand product usage. You can disable
              non-essential cookies in your browser settings without affecting core functionality.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">8. Children's Privacy</h2>
            <p>
              Ohgraffy is not directed at children under 13. We do not knowingly collect personal
              information from children under 13. If you believe a child has created an account,
              contact us and we will remove it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">9. Changes to This Policy</h2>
            <p>
              We may update this policy as our practices evolve. When we make significant changes,
              we will notify you via email. Continued use of the Service after changes take effect
              constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">10. Contact</h2>
            <p>
              Questions about this policy? Contact us at{" "}
              <a href="mailto:support@ohgraffy.com" className="underline hover:text-foreground">
                support@ohgraffy.com
              </a>.
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
