import { Link } from "react-router"

export function TermsOfService() {
  return (
    <div className="min-h-screen">
      <header className="border-b border-border">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center">
          <Link to="/" className="text-lg font-semibold tracking-tight">
            oh<span className="text-giraffy-body">graffy</span>
          </Link>
        </div>
      </header>
      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-12">Last updated: June 5, 2026</p>

        <div className="space-y-8 text-muted-foreground leading-relaxed">
          <p>
            Thank you for using Ohgraffy. By accessing or using our Service, you agree to these Terms.
            If you do not agree, do not use the Service.
          </p>

          <p>
            When we say "Company", "we", "our", or "us" in this document, we are referring to Ohgraffy.
            When we say "Service", we mean the Ohgraffy platform at ohgraffy.com and app.ohgraffy.com,
            including the comic generation engine and all related features.
            When we say "You" or "your", we are referring to you, the person or organization using the Service.
          </p>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">1. Account Terms</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>You must be at least 13 years old to use the Service.</li>
              <li>You must sign in via Google SSO. You are responsible for maintaining the security of your Google account.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>You must be a human. Accounts registered by bots or automated methods are not permitted.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">2. Description of Service</h2>
            <p>
              Ohgraffy is an AI-powered storytelling platform. You provide story inputs, character
              descriptions, and image references. The Service generates comics and visual narratives
              from your inputs. You can edit, export, and share the resulting content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">3. Payment and Billing</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>The Service offers a free Starter plan and paid subscription plans.</li>
              <li>Paid subscriptions are billed monthly. Your 30-day billing cycle begins on the date you subscribe.</li>
              <li>All payments are processed securely by Stripe. We do not store your payment card details.</li>
              <li>Prices are listed in USD. You are responsible for any applicable taxes.</li>
              <li>We may change pricing with 30 days notice. Existing subscriptions are honored until the end of the current billing period.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">4. Cancellation</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>You may cancel your subscription at any time through your account settings.</li>
              <li>Cancellation takes effect at the end of your current billing period. You retain access to paid features until then.</li>
              <li>After cancellation, your account reverts to the free Starter plan. Your content remains accessible.</li>
              <li>If you wish to delete your account entirely, contact us at support@ohgraffy.com. We will delete all your data within 30 days.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">5. Refund Policy</h2>
            <p>
              All purchases are final. We do not offer refunds for subscription payments. Because
              the Service provides immediate access to AI-generated content upon payment, the digital
              nature of the product means we cannot reverse delivery. You may cancel at any time to
              prevent future charges.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">6. Content Ownership</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>You retain full ownership of the content you provide to the Service: your story inputs, uploaded images, and any text you write.</li>
              <li>You own the comics and visual content generated by the Service from your inputs.</li>
              <li>We do not claim any intellectual property rights over your content.</li>
              <li>By using the Service, you grant us a limited license to process your content solely for the purpose of providing the Service to you. This license ends when you delete your content or account.</li>
              <li>You are responsible for ensuring your uploaded content (especially image references) does not infringe on third-party rights.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">7. Acceptable Use</h2>
            <p className="mb-2">You agree not to use the Service to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Generate content that is illegal, harmful, threatening, abusive, harassing, defamatory, or sexually exploitative.</li>
              <li>Generate content depicting minors in harmful or inappropriate situations.</li>
              <li>Impersonate another person without their consent using uploaded image references.</li>
              <li>Infringe on the intellectual property rights of others.</li>
              <li>Attempt to reverse-engineer, exploit, or overload the Service.</li>
            </ul>
            <p className="mt-2">We reserve the right to suspend or terminate accounts that violate these terms without notice.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">8. Service Availability</h2>
            <p>
              The Service is provided on an "as is" and "as available" basis. We do not guarantee
              uninterrupted access. We may modify, suspend, or discontinue features at any time. We will
              make reasonable efforts to notify you of significant changes.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Ohgraffy shall not be liable for any indirect,
              incidental, special, consequential, or punitive damages, or any loss of profits or
              revenue, whether incurred directly or indirectly, or any loss of data, use, or goodwill.
              In no event shall our aggregate liability exceed the amount you paid us in the 12 months
              preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">10. Changes to These Terms</h2>
            <p>
              We may update these Terms from time to time. When we make significant changes, we will
              notify you via email. Continued use of the Service after changes take effect constitutes
              acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-foreground mb-3">11. Contact</h2>
            <p>
              Questions about these Terms? Contact us at{" "}
              <a href="mailto:support@ohgraffy.com" className="underline hover:text-foreground">
                support@ohgraffy.com
              </a>.
            </p>
          </section>
        </div>
      </main>
    </div>
  )
}
